import { Html, Head, Main, NextScript } from "next/document";
import { theme } from "../theme/theme";
import { ColorModeScript } from "@chakra-ui/react";

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <body>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
